name = "beacon"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
mist = ">= 5.0.0 and < 6.0.0"
pog = ">= 4.0.0 and < 5.0.0"
envoy = ">= 1.0.0 and < 2.0.0"
gleam_crypto = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
